# Generated by Django 5.1 on 2024-10-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
